---

- hosts: database

  handlers:
    - name: restart_mysql
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:

    - name: 'Instala dependências no SO'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - mysql-server-5.6
        - python-mysqldb

    - name: 'Cria database no MySQL'
      mysql_db:
        name: "{{ wp_db_name }}"
        login_user: root
        state: present

    - name: 'Cria acessos no MySQL'
      mysql_user:
        name: "{{ wp_db_user }}"
        password: "{{ wp_db_password }}"
        priv: "{{ wp_db_name }}.*:ALL"
        login_user: root
        state: present
        host: "{{ item }}"
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - "{{ wp_host_ip }}"

    - name: 'Configura MySQL'
      copy:
        src: 'files/my.cnf'
        dest: '/etc/mysql/my.cnf'
      become: yes
      notify:
        - restart_mysql

- hosts: wordpress

  handlers:
    - name: restart_apache
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:

    - name: 'Instala dependências no SO'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - php5
        - php5-gd
        - php5-mcrypt
        - php5-mysql
        - apache2
        - libapache2-mod-php5
        - libssh2-php

    - name: 'Baixa Wordpress'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'

    - name: 'Descompacta Wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www/'
        remote_src: yes
      become: yes

    - name: 'Copia wp-config'
      copy:
        src: "{{ wp_dir }}/wp-config-sample.php"
        dest: "{{ wp_dir }}/wp-config.php"
        remote_src: yes
      become: yes

    - name: 'Configura wp-config'
      replace:
        path: "{{ wp_dir }}/wp-config.php"
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'localhost', value: "{{ wp_db_ip }}" }
        - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
        - { regex: 'username_here', value: "{{ wp_db_user }}" }
        - { regex: 'password_here', value: "{{ wp_db_password }}" }
      become: yes

    - name: 'Configura Apache'
      copy:
        src: 'files/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify:
        - restart_apache
