---

- name: 'Baixa Wordpress'
  get_url:
    url: 'https://wordpress.org/latest.tar.gz'
    dest: '/tmp/wordpress.tar.gz'

- name: 'Descompacta Wordpress'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www/'
    remote_src: yes
  become: yes

- name: 'Copia wp-config'
  copy:
    src: "{{ wp_dir }}/wp-config-sample.php"
    dest: "{{ wp_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Configura wp-config'
  replace:
    path: "{{ wp_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: 'localhost', value: "{{ wp_db_host }}" }
    - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
    - { regex: 'username_here', value: "{{ wp_db_user }}" }
    - { regex: 'password_here', value: "{{ wp_db_password }}" }
  become: yes

- name: 'Configura Apache'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify:
    - restart_apache
